import type { Locale } from './locales';

export const privacy = {
  en: [
    ['The app', 'Overlazy processes photos, overlays and settings on your device. We cannot access them. The app needs no account and sends us no usage data. It has no ads, tracking or analytics. Deleting the app removes its local data; photos you saved to your library remain until you delete them there. If you share or print through another app, that app’s privacy policy applies.'],
    ['If you contact us', 'If you email us, we receive your address and message to answer you. An optional beta-feedback email draft may include the app version and device details; you can edit it before sending. Apple handles TestFlight feedback under its own policy. We keep correspondence only as long as needed to respond or meet legal obligations.'],
    ['This website', 'The site uses no analytics or tracking cookies. It saves your language choice in your browser. GitHub Pages hosts the site and processes visitors’ IP addresses for security. GitHub may process data outside the EU; its privacy statement explains the details.'],
    ['Contact and your rights', 'Johannes Fahrenkrug, Parkstraße 20, 13585 Berlin, Germany, is responsible for Overlazy. Our legal basis for answering enquiries and operating and securing the site is legitimate interest (GDPR Article 6(1)(f)); legally required retention is based on Article 6(1)(c). Where applicable, you can request access, correction, deletion, restriction or portability, object to processing, and complain to a data protection authority. Contact us at johannes@springenwerk.com.']
  ],
  de: [
    ['Die App', 'Overlazy verarbeitet Fotos, Overlays und Einstellungen auf deinem Gerät. Wir haben darauf keinen Zugriff. Die App benötigt kein Konto und sendet uns keine Nutzungsdaten. Sie enthält keine Werbung, kein Tracking und keine Analysefunktionen. Wenn du die App löschst, werden ihre lokalen Daten entfernt; in deiner Fotomediathek gespeicherte Bilder bleiben dort, bis du sie löschst. Wenn du Bilder über eine andere App teilst oder druckst, gilt deren Datenschutzerklärung.'],
    ['Wenn du uns kontaktierst', 'Wenn du uns eine E-Mail schickst, erhalten wir deine Adresse und Nachricht, um dir zu antworten. Ein optionaler E-Mail-Entwurf für Beta-Feedback kann App-Version und Gerätedaten enthalten; du kannst ihn vor dem Absenden bearbeiten. Apple verarbeitet TestFlight-Feedback nach seinen eigenen Bestimmungen. Wir bewahren Korrespondenz nur so lange auf, wie es für die Antwort oder gesetzliche Pflichten nötig ist.'],
    ['Diese Website', 'Die Website verwendet keine Analysefunktionen oder Tracking-Cookies. Sie speichert deine Sprachwahl im Browser. GitHub Pages hostet die Website und verarbeitet IP-Adressen von Besuchern zur Sicherheit. GitHub kann Daten außerhalb der EU verarbeiten; Einzelheiten stehen in seiner Datenschutzerklärung.'],
    ['Kontakt und deine Rechte', 'Verantwortlich für Overlazy ist Johannes Fahrenkrug, Parkstraße 20, 13585 Berlin, Deutschland. Rechtsgrundlage für die Beantwortung von Anfragen sowie Betrieb und Sicherheit der Website ist unser berechtigtes Interesse (Art. 6 Abs. 1 lit. f DSGVO); eine gesetzlich vorgeschriebene Aufbewahrung beruht auf Art. 6 Abs. 1 lit. c DSGVO. Soweit anwendbar, kannst du Auskunft, Berichtigung, Löschung, Einschränkung oder Datenübertragbarkeit verlangen, der Verarbeitung widersprechen und dich bei einer Datenschutzaufsichtsbehörde beschweren. Kontakt: johannes@springenwerk.com.']
  ],
  es: [
    ['La app', 'Overlazy procesa fotos, superposiciones y ajustes en tu dispositivo. No tenemos acceso a ellos. La app no requiere cuenta ni nos envía datos de uso. No tiene publicidad, seguimiento ni analíticas. Al eliminar la app se borran sus datos locales; las fotos guardadas en tu biblioteca permanecen allí hasta que las elimines. Si compartes o imprimes mediante otra app, se aplica la política de privacidad de esa app.'],
    ['Si nos contactas', 'Si nos escribes por correo, recibimos tu dirección y mensaje para responderte. Un borrador opcional de comentarios de la beta puede incluir la versión de la app y datos del dispositivo; puedes editarlo antes de enviarlo. Apple gestiona los comentarios de TestFlight según su propia política. Conservamos la correspondencia solo mientras sea necesaria para responder o cumplir obligaciones legales.'],
    ['Este sitio web', 'El sitio no utiliza analíticas ni cookies de seguimiento. Guarda tu idioma en el navegador. GitHub Pages aloja el sitio y procesa las direcciones IP de los visitantes por motivos de seguridad. GitHub puede procesar datos fuera de la UE; su declaración de privacidad ofrece más detalles.'],
    ['Contacto y tus derechos', 'El responsable de Overlazy es Johannes Fahrenkrug, Parkstraße 20, 13585 Berlín, Alemania. La base jurídica para responder consultas y operar y proteger el sitio es nuestro interés legítimo (artículo 6(1)(f) del RGPD); la conservación exigida por ley se basa en el artículo 6(1)(c). Cuando corresponda, puedes solicitar acceso, rectificación, supresión, limitación o portabilidad, oponerte al tratamiento y reclamar ante una autoridad de protección de datos. Contacto: johannes@springenwerk.com.']
  ],
  'pt-BR': [
    ['O app', 'O Overlazy processa fotos, overlays e configurações no seu dispositivo. Não temos acesso a esses dados. O app não exige conta nem nos envia dados de uso. Não contém publicidade, rastreamento ou análise de uso. Ao excluir o app, seus dados locais são removidos; fotos salvas na biblioteca permanecem lá até que você as exclua. Se compartilhar ou imprimir por outro app, a política de privacidade desse app se aplica.'],
    ['Se você entrar em contato', 'Se nos enviar um e-mail, receberemos seu endereço e mensagem para responder. Um rascunho opcional de feedback da versão beta pode incluir a versão do app e dados do dispositivo; você pode editá-lo antes de enviar. A Apple trata o feedback do TestFlight conforme sua própria política. Guardamos a correspondência apenas pelo tempo necessário para responder ou cumprir obrigações legais.'],
    ['Este site', 'O site não usa análise de uso nem cookies de rastreamento. Ele salva sua escolha de idioma no navegador. O GitHub Pages hospeda o site e processa endereços IP dos visitantes para fins de segurança. O GitHub pode processar dados fora da UE; sua declaração de privacidade traz mais detalhes.'],
    ['Contato e seus direitos', 'O responsável pelo Overlazy é Johannes Fahrenkrug, Parkstraße 20, 13585 Berlim, Alemanha. A base legal para responder a consultas e operar e proteger o site é nosso interesse legítimo (artigo 6(1)(f) do RGPD); a retenção exigida por lei se baseia no artigo 6(1)(c). Quando aplicável, você pode solicitar acesso, correção, exclusão, restrição ou portabilidade, opor-se ao tratamento e reclamar a uma autoridade de proteção de dados. Contato: johannes@springenwerk.com.']
  ],
  fr: [
    ['L’application', 'Overlazy traite les photos, les superpositions et les réglages sur votre appareil. Nous n’y avons pas accès. Aucun compte n’est nécessaire et l’application ne nous envoie aucune donnée d’utilisation. Elle ne contient ni publicité, ni suivi, ni analyse d’audience. La suppression de l’application efface ses données locales ; les photos enregistrées dans votre photothèque y restent jusqu’à leur suppression. Si vous partagez ou imprimez via une autre application, sa politique de confidentialité s’applique.'],
    ['Si vous nous contactez', 'Si vous nous écrivez, nous recevons votre adresse e-mail et votre message pour vous répondre. Un brouillon facultatif de retour sur la bêta peut contenir la version de l’application et des informations sur l’appareil ; vous pouvez le modifier avant l’envoi. Apple gère les retours TestFlight selon sa propre politique. Nous conservons la correspondance uniquement le temps nécessaire pour répondre ou respecter nos obligations légales.'],
    ['Ce site web', 'Le site n’utilise ni analyse d’audience ni cookies de suivi. Il enregistre votre choix de langue dans votre navigateur. GitHub Pages héberge le site et traite les adresses IP des visiteurs à des fins de sécurité. GitHub peut traiter des données hors de l’UE ; sa déclaration de confidentialité fournit des précisions.'],
    ['Contact et vos droits', 'Le responsable d’Overlazy est Johannes Fahrenkrug, Parkstraße 20, 13585 Berlin, Allemagne. La base juridique pour répondre aux demandes ainsi que pour exploiter et sécuriser le site est notre intérêt légitime (article 6(1)(f) du RGPD) ; la conservation imposée par la loi repose sur l’article 6(1)(c). Le cas échéant, vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou la portabilité, vous opposer au traitement et saisir une autorité de protection des données. Contact : johannes@springenwerk.com.']
  ],
  ja: [
    ['アプリ', 'Overlazyは写真、オーバーレイ、設定を端末内で処理します。私たちはこれらにアクセスできません。アカウントは不要で、アプリの利用データも送信されません。広告、トラッキング、利用状況の分析はありません。アプリを削除するとアプリ内のデータは消去されますが、写真ライブラリに保存した写真はそこで削除するまで残ります。他のアプリで共有や印刷をする場合は、そのアプリのプライバシーポリシーが適用されます。'],
    ['お問い合わせ', 'メールでお問い合わせいただくと、返信のためにメールアドレスとメッセージを受け取ります。任意のベータ版フィードバック用メール下書きには、アプリのバージョンや端末情報が含まれる場合があります。送信前に編集できます。TestFlightのフィードバックはAppleの方針に従って処理されます。連絡内容は返信または法的義務に必要な期間のみ保存します。'],
    ['このウェブサイト', '当サイトは利用状況の分析やトラッキングCookieを使用しません。選択した言語はブラウザに保存されます。GitHub Pagesはサイトをホストし、セキュリティのため訪問者のIPアドレスを処理します。GitHubはEU域外でデータを処理する場合があります。詳細はGitHubのプライバシーステートメントをご覧ください。'],
    ['連絡先と権利', 'Overlazyの責任者はJohannes Fahrenkrug（Parkstraße 20, 13585 Berlin, Germany）です。お問い合わせへの対応とサイトの運営・安全確保の法的根拠は正当な利益（GDPR第6条1項(f)）、法令上必要な保存は同項(c)です。適用される場合、アクセス、訂正、削除、処理の制限、データポータビリティを請求し、処理に異議を申し立て、データ保護監督機関に苦情を申し立てることができます。連絡先：johannes@springenwerk.com。']
  ],
  ko: [
    ['앱', 'Overlazy는 사진, 오버레이 및 설정을 기기에서 처리합니다. 개발자는 이 데이터에 접근할 수 없습니다. 계정이 필요하지 않으며 앱 사용 데이터가 개발자에게 전송되지 않습니다. 광고, 추적 및 사용 분석도 없습니다. 앱을 삭제하면 앱의 로컬 데이터가 제거되지만 사진 보관함에 저장한 사진은 그곳에서 삭제할 때까지 남습니다. 다른 앱을 통해 공유하거나 인쇄하면 해당 앱의 개인정보 처리방침이 적용됩니다.'],
    ['문의할 때', '이메일로 문의하면 답변을 위해 이메일 주소와 메시지를 받습니다. 선택 사항인 베타 피드백 이메일 초안에는 앱 버전과 기기 정보가 포함될 수 있으며 보내기 전에 수정할 수 있습니다. TestFlight 피드백은 Apple의 자체 방침에 따라 처리됩니다. 문의 내용은 답변 또는 법적 의무에 필요한 기간만 보관합니다.'],
    ['이 웹사이트', '사이트는 사용 분석이나 추적 쿠키를 사용하지 않습니다. 선택한 언어는 브라우저에 저장됩니다. GitHub Pages는 사이트를 호스팅하며 보안을 위해 방문자의 IP 주소를 처리합니다. GitHub는 EU 외 지역에서 데이터를 처리할 수 있습니다. 자세한 내용은 GitHub 개인정보 보호정책을 참조하세요.'],
    ['연락처 및 권리', 'Overlazy의 책임자는 Johannes Fahrenkrug, Parkstraße 20, 13585 Berlin, Germany입니다. 문의에 답하고 사이트를 운영·보호하는 법적 근거는 정당한 이익(GDPR 제6조 제1항 (f))이며, 법률상 요구되는 보관은 같은 항 (c)에 근거합니다. 해당되는 경우 열람, 정정, 삭제, 처리 제한 또는 이동을 요청하고 처리에 이의를 제기하거나 개인정보 보호 감독기관에 불만을 제기할 수 있습니다. 연락처: johannes@springenwerk.com.']
  ]
} as const satisfies Record<Locale, readonly (readonly [string, string])[]>;
